name: test load and parse

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'README.md'
  pull_request:

jobs:
  plugin-load:
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: DEBUG
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependences 
      run: uv sync --group test

    - name: Run Load Tests
      run: uv run pytest tests/test_load.py

  bilibili-test:
    needs: plugin-load
    uses: ./.github/actions/pytest.yml
    with:
      python-version: "3.12"
      job-name: "Bilibili Tests"
      test-file: "tests/test_bilibili.py"


  weibo-test:
    needs: plugin-load
    uses: ./.github/actions/pytest.yml
    with:
      python-version: "3.12"
      job-name: "Weibo Tests"
      test-file: "tests/test_weibo.py"

  twitter-test:
    needs: plugin-load
    uses: ./.github/actions/pytest.yml
    with:
      python-version: "3.12"
      job-name: "Twitter Tests"
      test-file: "tests/test_x.py"



  acfun-test:
    needs: plugin-load
    uses: ./.github/actions/pytest.yml
    with:
      python-version: "3.12"
      job-name: "Acfun Tests"
      test-file: "tests/test_acfun.py"

  ncm-test:
    needs: plugin-load
    uses: ./.github/actions/pytest.yml
    with:
      python-version: "3.12"
      job-name: "NCM Tests"
      test-file: "tests/test_ncm.py"

  douyin-test:
    needs: plugin-load
    uses: ./.github/actions/pytest.yml
    with:
      python-version: "3.12"
      job-name: "Douyin Tests"
      test-file: "tests/test_douyin.py"
      
  xhs-test:
    needs: plugin-load
    uses: ./.github/actions/pytest.yml
    with:
      python-version: "3.12"
      job-name: "Xiaohongshu Tests"
      test-file: "tests/test_xhs.py"